### ISSUE TITLE
能不能给 large.dict 添加“子”字的轻声zi？

### ISSUE THREAD

**Issue by Jian787** [amzxyz/RIME-LMDG#3]
我和我的朋友想在万象语言模型的基础上做一个带声调输入的拼音输入法（类似于地球拼音）。可不可以给给 large.dict 添加“子”字的轻声zi？防止一些没有收录的词的第二个字是轻声的子

**Comment by amzxyz** [comment]
单字其实不应该按轻声修订，我会在词汇中具体的场景下使用轻声，比如常见得爸爸、儿子，但我不能把这些字的单个字表做成轻声，我认为这是不规范的，请见谅！

**Comment by Jian787** [comment]
那好吧。那这样“头”、“家“、”卜“、”裳“字的轻声你是不是要删掉……

**Comment by Jian787** [comment]
所以“头”、“家“、”卜“、”裳“字的轻声会不会删？

**Comment by amzxyz** [comment]
> 所以“头”、“家“、”卜“、”裳“字的轻声会不会删？

不会删掉，是按照实际读音修订

**Comment by amzxyz** [comment]
> 所以“头”、“家“、”卜“、”裳“字的轻声会不会删？

你说的单字啊，删掉

**Comment by Jian787** [comment]
我这个issue就是在说 large.dict 里的单字啊
