### ISSUE TITLE
能否给出一个更加详细的指南

### ISSUE THREAD

**Issue by rainzee** [amzxyz/RIME-LMDG#4]
目前的指南，基本侧重在了如何 build，而具体使用只有寥寥几句，是否可以给出一个更加详细的指南呢

**Comment by amzxyz** [comment]
https://github.com/amzxyz/RIME-LMDG/wiki/%E8%AF%AD%E8%A8%80%E6%A8%A1%E5%9E%8B%E5%8F%82%E6%95%B0%E9%85%8D%E7%BD%AE%E8%AF%B4%E6%98%8E

方案里面加上这一段即可

**Comment by yizhimuzhuozi** [comment]
https://www.00000520.xyz/article/RIME-LMDG 
其实安装很简单，就是写的太复杂了。

**Comment by amzxyz** [comment]
其实我写了把那一段放进去然后他们其实觉得有点恍惚，认为写了那么多就这么简单难道，很好这件事情交给你们了！
