### ISSUE TITLE
“落下”、“要的”词打不出来

### ISSUE THREAD

**Issue by Jian787** [amzxyz/RIME-LMDG#5]
![Screenshot (54)](https://github.com/user-attachments/assets/6740231d-66c1-4d61-91ee-7a36b37ac387)
![Screenshot (55)](https://github.com/user-attachments/assets/c7fc25d0-b704-46d7-a34a-dad3e2e48527)
![Screenshot (56)](https://github.com/user-attachments/assets/9c0a6441-9e1c-46cc-9833-8d0508457727)

**Comment by amzxyz** [comment]
收到，修正

**Comment by z1073** [comment]
![image](https://github.com/user-attachments/assets/721201f0-f28c-44e4-9360-7bd7c2b28b38)
